[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/dc0d/workerpool"
  version = "v3.0.3"

[[constraint]]
  name = "github.com/gofrs/uuid"
  version = "3.0.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/tomb.v2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"
